defaults:
  - env: cartpole

distraction:
  type: null
  location: "background"

logdir: ./logdir
seed: 0
num_envs: 1
steps: 1e6
eval_eps: 10
image_size: [64, 64]
grayscale: False
replay_size: 2e6
dataset: {batch: 50, length: 51, oversample_ends: True}
precision: 16
jit: True

# Natural Background
max_videos: 100

# Agent
train_steps: 1
clip_rewards: identity
expl_noise: 0.0
expl_behavior: greedy
expl_until: 0
eval_noise: 0.0
eval_state_mean: False

# World Model
encoder: {depth: 48, act: elu, kernels: [4, 4, 4, 4], keys: [image]}
reward_head: {layers: 4, units: 400, act: elu, dist: mse}
discount_head: {layers: 4, units: 400, act: elu, dist: binary}
loss_scales: {swav: 1.0, temp: 1.0, norm: 1.0, kl: 1.0, reward: 1.0, discount: 1.0}
kl: {free: 0.0, forward: False, balance: 0.8, free_avg: True}
model_opt: {opt: adam, lr: 3e-4, eps: 1e-5, clip: 100, wd: 1e-6}
aug: {max_delta: 3.0, same_across_time: True, bilinear: True}
freeze_prototypes_iters: 10000
ema_update_every: 1
ema_update_fraction: 0.05

# Actor Critic
actor: {layers: 4, units: 400, act: elu, dist: tanh_normal, min_std: 0.1}
critic: {layers: 4, units: 400, act: elu, dist: mse}
actor_opt: {opt: adam, lr: 1e-4, eps: 1e-5, clip: 100, wd: 1e-6}
critic_opt: {opt: adam, lr: 1e-4, eps: 1e-5, clip: 100, wd: 1e-6}
discount_lambda: 0.95
imag_horizon: 15
actor_grad_mix: 0.1
slow_target: True
slow_target_update: 100
slow_target_fraction: 1

# Exploration
expl_extr_scale: 0.0
expl_intr_scale: 1.0
expl_opt: {opt: adam, lr: 3e-4, eps: 1e-5, clip: 100, wd: 1e-6}
expl_head: {layers: 4, units: 400, act: elu, dist: mse}
disag_target: stoch
disag_log: True
disag_models: 10
disag_offset: 1
disag_action_cond: True
expl_model_loss: kl


time_limit: 1000
action_repeat: 2
eval_every: 1e4
log_every: 1e4
prefill: 1000
train_every: 5
pretrain: 100
pred_discount: False
grad_heads: [reward]
rssm: {hidden: 200, deter: 200, discrete: False, sinkhorn_eps: 0.0125}
model_opt.lr: 3e-4
actor_opt.lr: 8e-5
critic_opt.lr: 8e-5
actor_ent: 1e-4
discount: 0.99
actor_grad: dynamics
kl.free: 1.0
dataset.oversample_ends: False
